st10299399POE/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using st10299399POE.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using System.Data.SqlClient;

namespace st10299399POE.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public HomeController(ILogger<HomeController> logger, IHttpContextAccessor httpContextAccessor)
        {
            _logger = logger;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            int? userID = HttpContext.Session.GetInt32("UserID");
            return View(userID);
        }

        public IActionResult MyWork()
        {
            List<productTable> products = productTable.GetAllProducts();
            int? userID = _httpContextAccessor.HttpContext.Session.GetInt32("UserID");
            
            ViewData["Products"] = products;
            ViewData["UserID"] = userID;
            return View();
        }

        public IActionResult AboutUS()
        {
            return View();
        }

        public IActionResult ContactUs()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult ShowLoginForm()
        {
            return View("LoginForm");
        }

        public IActionResult ShowSignupForm()
        {
            return View("SignupForm");
        }

        public IActionResult ViewOrders(int userID)
        {
            List<transactionTable> orders = GetOrdersForUser(userID);
            return View(orders);
        }

        private List<transactionTable> GetOrdersForUser(int userID)
        {
            List<transactionTable> orders = new List<transactionTable>();
            string connectionString = "Server=tcp:ethan1-sql-server.database.windows.net,1433;Initial Catalog=ethan1-sql-database;Persist Security Info=False;User ID=EthanP1;Password=Landfour66;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
                string sql = "SELECT * FROM transactionTable WHERE userID = @UserID";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@UserID", userID);
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            transactionTable order = new transactionTable();
                            order.OrderID = reader.GetInt32(0);
                            order.UserID = reader.GetInt32(1);
                            order.ProductID = reader.GetInt32(2);
                            order.ProductName = reader.GetString(3);
                            orders.Add(order);
                        }
                    }
                }
            }
            return orders;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

st10299399POE/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using st10299399POE.Models;

namespace st10299399POE.Controllers
{
    public class LoginController : Controller
    {

        private readonly LoginModel login;

        public LoginController()
        {
            login = new LoginModel();
        }

        [HttpPost]
        public ActionResult LoginForm(string email, string name)
        {
            var loginModel = new LoginModel();
            int userID = loginModel.SelectUser(email, name);
            if (userID != -1)
            {
                HttpContext.Session.SetInt32("UserID", userID);
                return RedirectToAction("MyWork", "Home", new { userID = userID });
            }
            else
            {
                return View("LoginFailed");
            }
        }

        public ActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

st10299399POE/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using st10299399POE.Models;

namespace st10299399POE.Controllers
{
    public class ProductController : Controller
    {
        public productTable prodtbl = new productTable();

        [HttpPost]
        public ActionResult MyWork(productTable products)
        {
            var result2 = prodtbl.insert_Product(products);
            return RedirectToAction("MyWork", "Home");
        }

        [HttpGet]
        public ActionResult myWork()
        {
            return View(prodtbl);
        }
    }
}

st10299399POE/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Mvc;
using st10299399POE.Models;
using System.Data.SqlClient;

namespace st10299399POE.Controllers
{
    public class TransactionController : Controller
    {
        [HttpPost]
        public ActionResult PlaceOrder(int userID, int productID)
        {
            try
            {
                using (SqlConnection con = new SqlConnection(productTable.con_string))
                {
                    string sql = "INSERT INTO transactionTable (userID, productID) VALUES (@UserID, @ProductID)";

                    using (SqlCommand cmd = new SqlCommand(sql, con))
                    {
                        cmd.Parameters.AddWithValue("@UserID", userID);
                        cmd.Parameters.AddWithValue("@ProductID", productID);

                        con.Open();

                        int rowsAffected = cmd.ExecuteNonQuery();

                        con.Close();

                        if (rowsAffected > 0)
                        {
                            return View("OrderSuccessfull");
                        }
                        else
                        {
                            return View("OrderFailed");
                        }
                    }
                }
            }
            catch (Exception)
            {
                return View("OrderFailed");
            }
        }
    }
}

st10299399POE/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using st10299399POE.Models;

namespace st10299399POE.Controllers
{
    public class UserController : Controller
    {
        public userTable usrtbl = new userTable();

        [HttpPost]
        public ActionResult SignUpForm(userTable Users)
        {
            var result = usrtbl.insert_User(Users);
            return RedirectToAction("ShowLoginForm", "Home");
        }

        [HttpGet]
        public ActionResult About()
        {
            return View(usrtbl);
        }
    }
}

st10299399POE/Views/Home/AboutUS.cshtml
@model st10299399POE.Models.userTable
@{
    ViewData["Title"] = "AboutUS";
}


<style>
    .row {
        display: flex;
        justify-content: center; 
    }

    .column {
        flex: 1;
    }

    .card {
        display: flex;
        flex-direction: row; 
    }

    .container {
        padding: 20px;
    }
</style>

<div class="about-section">
    <h1>About Us </h1>
    <h2 style ="text-align: center"> Who are we?</h2>
    <p>
        We are KhumaloCraft a place were all artisans can share and sell their fantastic work. All across the world their is a lot of diffrent people with lots of unique
        and buetiful skills. On this platform they are able to put up pictures of what they have crafted and sell it to whomever is interested. This platform is respectful and
        for people who love art.
    </p>
</div>

<h2 style="text-align:center">Our Team</h2>
<div class="row">
    <div class="column">
        <img src="/images/jameskhumalo.jpeg" alt="James" style="width:100%" height="350">
        <div class="card">           
            <div class="container">
                <h2>James Khumalo</h2>
                <p class="title"><h3>CEO & Founder</h3></p>
                <p>My name is James the founder and CEO of KhumaloCraft. I started this business as I love art and craftmanship, but I found out that there are tons of
                    artisans who do not have a platform or place to sell and display their work. Thats why I started this business a place where we all connect.
                </p>
            </div>
        </div>
    </div>

    <div class="column">
        <img src="/images/pexels-jeffrey-reed-769772.jpg" alt="Ethan" style="width:100%" height="350">
        <div class="card">
            <div class="container">
                <h2>Ethan Visagie</h2>
                <p class="title"><h3>Head of IT </h3></p>
                <p>Im the head of IT for Mr. James's business. I helped him create his website and make his dream a reality. I am here to help fix any issues
                    and improve the current website if needed.
                </p>
            </div>
        </div>
    </div>

    <div class="column">
        <img src="/images/pexels-pixabay-415829.jpg" alt="Jane" style="width:100%" height="350">
        <div class="card">
            
            <div class="container">
                <h2>Jane Conradie</h2>
                <p class="title"><h3>Customer Relations</h3></p>
                <p>Im the person that is here to help with any customer complaints or issues they might have with the website.
                    I also report any bugs or improvements the customers suggest to the Head of IT so that they can solve those problems.
                    If there are any problems with the service of our business please contact me so that I can report them to our CEO.
                </p>
                <p> khumaloCraft@gmail.com<br />
                    Contact number: (022) 689 1584</p>
            </div>
        </div>
    </div>

    <div class="column">
        <img src="/images/pexels-vinicius-wiesehofer-1130626.jpg" alt="Jannite" style="width:100%" height="350">
        <div class="card">
 
            <div class="container">
                <h2>Jannite Slaaiblaar</h2>
                <p class="title"><h3>Head of Art</h3></p>
                <p>
                    Im the person that works with the team to approve if the art that is submitted is safe to be posted online. We look carefully and have deep
                    discussing on wheter your art applies with our terms and regulations. We do this to be safe and make sure that our website does not get used for
                    wrong reasons.My contact information below for if we do not send you a message to say that your art is publised or not.
                </p>
                <p> khumaloArtsales@gmail.com<br />
                    Contact number: (022) 111 458</p>
            </div>
        </div>
    </div>
</div>

st10299399POE/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "ContactUs";
}

<h1> Contact Us</h1>

<h2 style="text-align:center">How to contact us:</h2>
<p style ="text-align:center">
    Tel:      (022) 689 1584 <br/>
    Whatsapp: 083 555 1677 <br/>
    Email:    khumaloCraft@gmail.com
</p>

st10299399POE/Views/Home/Index.cshtml
@model int?
@{
    ViewData["Title"] = "Home Page";
     var userID = Model;
}

<style>
    body
    {
        background-image: url('images/WPage.png');
        background-size: 100% 100%;
        background-repeat: no-repeat;
    } 

    footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.8);
        padding: 10px;
    }

    .card {
        margin: 0 auto; 
        width: 80%; 
    }

    .card-body {
        padding: 10px;
    }

</style>

@if (!userID.HasValue)
{
    <div class="col-md-3">
        <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Login or Sign Up</h5>
                    <p class="card-text">Please login or sign up to access more features.</p>
                    <a href="@Url.Action("ShowLoginForm", "Home")" class="btn btn-primary">Login</a>
                    <a href="@Url.Action("ShowSignUpForm", "Home")" class="btn btn-secondary">Sign Up</a>
                </div>
            </div>
        </div>
}
else
{
    <form method="post" action="@Url.Action("Logout", "Login")">
        <button type="submit" class="btn btn-primary">Sign Out</button>
    </form>
}

st10299399POE/Views/Home/LoginForm.cshtml
<style>
        body {
            background-image: url('/images/bg1.jpeg');
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
        }

        .form-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100%;
            width: 100%
        }

        form {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 10px;
        }

        footer{
            position: fixed;
            bottom: 0;
            width: 100%;
            background-color: rgba(255, 255, 255, 0.8);
            padding: 10px;
        }
</style>



<body>
    <div class="form-container">
        <form asp-controller="Login" asp-action="LoginForm" method="post" style="text-align:center">
            <p>Please enter your first name and email:</p>
            <input type="text" name="name" placeholder="Name" required>
            <input type="text" name="email" placeholder="example@gmail.com" required>
            <button type="submit">Submit</button>
        </form>
    </div>
</body>

st10299399POE/Views/Home/MyWork.cshtml
@model int 
@* @model st10299399POE.Models.productTable; *@
@{
    ViewData["Title"] = "MyWork";
    var userID = ViewData["UserID"];
    var products = ViewData["Products"] as List<st10299399POE.Models.productTable>;
}

<h1>MyWork</h1>
    <style>

    .container-wrapper 
    {
        display: flex;
        justify-content: space-between; 
        width: 800px; 
        margin: 0 auto; 
    }
        .image-container 
        {
            text-align: center;
        }
</style>
@* <body>
        <div class="container-wrapper">
        <div style="border-style:solid; border-color:black; border-width:3px;">
        <div class ="image-container">
        <img src="/images/P1.webp" width="400" height="300" />
        <p>
        Autum Leafs Canvas Painting <br />
        By: Sonja Bruwer<br />
        Price: R5600
        </p>
        </div>
        </div>
        <div class="image-container">
        <div style="border-style:solid; border-color:black; border-width:3px;">
        <img src="/images/P2.webp" width="400" height="300" />
        <p>
        Peacock Canvas Painting <br />
        By: Alexandra Kramer<br />
        Price: R4000
        </p>
        </div>
        </div>
        </div>

        <div class="container-wrapper">
        <div style="border-style:solid; border-color:black; border-width:3px;">
        <div class="image-container">
        <img src="/images/P3.jpg" width="400" height="300" />
        <p>
        Clay Cooking Pots <br />
        By: Sisile Mbeke <br />
        Price: R300
        </p>
        </div>
        </div>
        <div class="image-container">
        <div style="border-style:solid; border-color:black; border-width:3px;">
        <img src="/images/P5.jpeg" width="400" height="300" />
        <p>
        Handmade Coffee Mugs <br />
        By: Dembe Buvuma <br />
        Price: R60 <br />
        Special: R100 for 2
        </p>
        </div>
        </div>
        </div>

        <div class="container-wrapper">
        <div style="border-style:solid; border-color:black; border-width:3px;">
        <div class="image-container">
        <img src="/images/p7.webp" width="400" height="300" />
        <p>
        Sea Braclets and Necklaces <br />
        By: Oscar Piastri <br />
        Price: R150
        </p>
        </div>
        </div>
        <div class="image-container">
        <div style="border-style:solid; border-color:black; border-width:3px;">
        <img src="/images/p6.webp" width="400" height="300" />
        <p>
        Crystal Necklaces <br />
        By: Oscar Piastri <br />
        Price: R100
        </p>
        </div>
        </div>
        </div>
        </body> *@

@if (userID != null)
{
    <p>User ID: @userID</p>
    <a href="@Url.Action("ViewOrders", "Home", new { userID = userID})" class="btn btn-primary">View Orders</a>
}

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <h2>All Products</h2>
            <table class="table">
            <thead>
            <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Category</th>
            <th>Availability</th>
            <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var product in products)
            {
            <tr>
            <td>@product.Name</td>
            <td>@product.Price</td>
            <td>@product.Category</td>
            <td>@product.Availability</td>
            <td>
            <form asp-controller="Transaction" asp-action="PlaceOrder" method="post">
            <input type="hidden" name="userID" value="@userID" />
            <input type="hidden" name="productID" value="@product.ProductID" />
            <button type="submit">Place Order</button>
            </form>
            </td>
            </tr>
            }
            </tbody>
            </table>
        </div>
        </div>
        </div>


@if (userID != null)
        {
            <body>
                <form asp-controller="Product" asp-action="MyWork" method="post">
                    <h2>Insert new products</h2>
                    <input type="text" name="Name" placeholder="Name" required>
                    <input type="text" name="Price" placeholder="Price" required>
                    <input type="text" name="Category" placeholder="Category" required>
@*                     <input type="text" name="Availability" placeholder="Availability: True/False" required> *@

                    <label for="Availability">Availability</label>
                    <select name="Availability">
                        <option value="1">In stock</option>
                        <option value="0">Out of stock</option>
                    </select>
                    <button type="submit">Submit</button>
                </form>
            </body>
        }

st10299399POE/Views/Home/SignUpForm.cshtml
<style>
    body {
        background-image: url('/images/bg4.jpg');
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
    }

    .form-container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex: 1;
    }

    form {
        background: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border-radius: 10px;
        text-align: center;
    }

    footer {
        position: fixed;
        bottom: 0;
        width: 100%;
        background-color: rgba(255, 255, 255, 0.8);
        padding: 10px;
    }
</style>

<body>
    <div class="form-container">
        <form asp-controller="User" asp-action="SignUpForm" method="post" style="text-align:center">
            <p> Sign Up</p>
            <input type="text" name="Name" placeholder="Name" required>
            <input type="text" name="Surname" placeholder="Surname" required>
            <input type="text" name="Email" placeholder="example@gmail.com" required>
            <button type="submit"> Submit</button>
        </form>
    </div>
</body>

st10299399POE/Views/Home/ViewOrders.cshtml
@model List<transactionTable>

<h1>Your Orders</h1>
<table class="table">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Product ID</th>
            <th>Product Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var order in Model)
        {
            <tr>
                <td>@order.OrderID</td>
                <td>@order.ProductID</td>
                <td>@order.ProductName</td>
            </tr>
        }
    </tbody>
</table>